<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 18.7 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.7');
$this->pageTitle('Listing 18.7');
?>
<h3><code>PizzaForm</code> für die Pflege von Pizzadaten</h3>
<pre>
&lt;?php
namespace Pizza\Form;

use Zend\Form\Element\Csrf;
use Zend\Form\Element\File;
use Zend\Form\Element\Hidden;
use Zend\Form\Element\MultiCheckbox;
use Zend\Form\Element\Select;
use Zend\Form\Element\Text;
use Zend\Form\Element\Textarea;
use Zend\Form\Element\Submit;
use Zend\Form\Form;
use Zend\Form\FormInterface;

class PizzaForm extends Form implements PizzaFormInterface
{
    public function addCsrfElement($name = 'tick')
    {
        $element = new Csrf($name);
        $this->add($element);
    }
        
    public function addIdElement($name = 'id')
    {
        $element = new Hidden($name);
        $this->add($element);
    }
        
    public function addStatusElement($options = array(), $name = 'status')
    {
        $element = new Select($name);
        $element->setLabel('Status');
        $element->setAttribute('class', 'span3');
        $element->setValueOptions($options);
        $this->add($element);
    }
    
    public function addNameElement($name = 'name')
    {
        $element = new Text($name);
        $element->setLabel('Name');
        $element->setAttribute('class', 'span3');
        $this->add($element);
    }
    
    public function addDescriptionElement($name = 'description')
    {
        $element = new Textarea($name);
        $element->setLabel('Beschreibung');
        $element->setAttribute('class', 'ckeditor');
        $this->add($element);
    }
    
    public function addPriceElement($name = 'price')
    {
        $element = new Text($name);
        $element->setLabel('Preis');
        $element->setAttribute('class', 'span3');
        $element->setAttribute('maxlength', '5');
        $this->add($element);
    }
    
    public function addCrustElement($options = array(), $name = 'crust_id')
    {
        $element = new Select($name);
        $element->setLabel('Pizzaboden');
        $element->setAttribute('class', 'span3');
        $element->setValueOptions($options);
        $this->add($element);
    }
    
    public function addToppingsElement($options = array(), $name = 'toppings')
    {
        $element = new MultiCheckbox($name);
        $element->setLabel('Pizzabeläge');
        $element->setValueOptions($options);
        $this->add($element);
    }
    
    public function addPictureElement($name = 'picture')
    {
        $element = new File($name);
        $element->setLabel('Bild-Upload');
        $this->add($element);
        
        $this->setAttribute('enctype','multipart/form-data');
    }
    
    public function addSubmitElement($name = 'save', $label = 'Speichern')
    {
        $element = new Submit($name);
        $element->setValue($label);
        $element->setAttribute('class', 'btn');
        $this->add($element);
    }
    
    public function bind($object, $flags = FormInterface::VALUES_NORMALIZED)
    {
        parent::bind($object, $flags);
        
        if ($this->get('toppings')) {
            $this->get('toppings')->setValue(
                array_keys($object->getToppings())
            );
        }
    }
}
</pre>
