<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 18.11 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.11');
$this->pageTitle('Listing 18.11');
?>
<h3>Geänderte <code>updateAction()</code> verarbeitet den Dateiupload</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Zend\Http\PhpEnvironment\Response;
use Zend\View\Model\ViewModel;
use Zend\Mvc\Controller\AbstractActionController;
use Pizza\Service\PizzaServiceInterface;

class AdminController extends AbstractActionController
{
    [...]
    
    public function updateAction()
    {
        [...]
        
        $form = $this->getPizzaService()->getForm('update');
        
        $prg = $this->fileprg($form);
        
        [...]
    }
    
    [...]
}
</pre>
