<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 18.1 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.1');
$this->pageTitle('Listing 18.1');
?>
<h3>Aufbau der Datenbank</h3>
<pre>
CREATE TABLE pizzas (
    id integer primary key, 
    status varchar(8), 
    name varchar(32), 
    description text, 
    price float, 
    url varchar(32), 
    crust_id integer, 
    FOREIGN KEY(crust_id) REFERENCES crusts(id)
);

CREATE TABLE crusts (
    id integer primary key, 
    name varchar(32), 
    costs float
);

CREATE TABLE toppings (
    id integer primary key, 
    name varchar(32), 
    costs float
);

CREATE TABLE pizzas_toppings (
    pizza_id integer, 
    topping_id integer, 
    FOREIGN KEY(pizza_id) REFERENCES pizzas(id), 
    FOREIGN KEY(topping_id) REFERENCES toppings(id)
);
</pre>
