<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 18.6 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.6');
$this->pageTitle('Listing 18.6');
?>
<h3><code>Module.php</code> injiziert <code>TableGateway</code>-Objekte bei Bedarf</h3>
<pre>
&lt;?php
namespace Pizza;

use Zend\Filter\StaticFilter;
[...]

class Module implements 
    BootstrapListenerInterface,
    ConfigProviderInterface, 
    AutoloaderProviderInterface
{
    public function onBootstrap(EventInterface $e)
    {
        [...]
        
        $sharedEventManager->attach(
            'Pizza\Service\PizzaService',
            'set-pizza-table',
            array($this, 'onTableSet')
        );
    }
    
    [...]
    
    public function onTableSet(EventInterface $e)
    {
        $type      = $e->getParam('type', 'pizza');
        $tableName = StaticFilter::execute($type, 'wordunderscoretocamelcase');
        $service   = $this->serviceLocator->get('Pizza\Service\Pizza');
        $form      = $this->serviceLocator->get('Pizza\Table\\' . $tableName);
        $service->setTable($form, $type);
    }
}
</pre>
