<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 18.9 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.9');
$this->pageTitle('Listing 18.9');
?>
<h3>Geänderter <code>PizzaFilter</code> für Dateiupload</h3>
<pre>
&lt;?php
namespace Pizza\Filter;

use Zend\InputFilter\InputFilter;

class PizzaFilter extends InputFilter
{
    public function init()
    {
        [...]

        $this->add(array(
            'type'       => 'Zend\InputFilter\FileInput',
            'name'       => 'picture',
            'required'   => false,
            'filters'    => array(
                array(
                    'name'    => 'FileRenameUpload',
                    'options' => array(
                        'target'    => LUIGI_ROOT . '/data/upload/tempfile.jpg',
                        'overwrite' => true,
                    ),
                ),
            ),
            'validators' => array(
                array(
                    'name'    => 'FileImageSize',
                    'options' => array(
                        'minWidth'  => 200, 'maxWidth'  => 200, 
                        'minHeight' => 150, 'maxHeight' => 150,
                    ),
                ),
                array(
                    'name'    => 'FileMimeType',
                    'options' => array(
                        'mimeType' => 'image/jpeg',
                    ),
                ),
            ),
        ));
    }
}
</pre>
