<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 18.2 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 18.2');
$this->pageTitle('Listing 18.2');
?>
<h3><code>ToppingTable</code> Klasse implementiert <code>Zend\Db\TableGateway</code></h3>
<pre>
&lt;?php
namespace Pizza\Table;

use Pizza\Entity\ToppingEntityInterface;
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;

class ToppingTable extends TableGateway
{
    public function __construct(Adapter $adapter, ToppingEntityInterface $entity)
    {
        $resultSet = new ResultSet();
        $resultSet->setArrayObjectPrototype($entity);
        
        parent::__construct('toppings', $adapter, null, $resultSet);
    }
    
    public function fetchOptions()
    {
        $select = $this->getSql()->select();
        $select->order('id');
        
        $options = array();
        
        foreach ($this->selectWith($select) as $row) {
            $options[$row->getId()] = $row->getName();
        }
        
        return $options;
    }
    
    public function fetchListByPizzaId($pizzaId)
    {
        $select = $this->getSql()->select();
        $select->join('pizzas_toppings', 'topping_id = id', array());
        $select->where->equalTo('pizza_id', $pizzaId);
        $select->order('id');

        $list = array();
        
        foreach ($this->selectWith($select) as $row) {
            $list[$row->getId()] = $row;
        }
        
        return $list;
    }
    
    public function fetchSingleById($id)
    {
        [...]
    }
}
</pre>
