<?php 
/**
 * ZF2 Buch Kapitel 18
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * namespace definition and usage
 */
use Blog\Entity\BlogEntity;

/**
 * Blog show view script
 * 
 * @package    Blog
 */

$blog = $this->blogData;  /* @var $blog BlogEntity */

$this->headTitle($blog->getTitle());
$this->pageTitle($blog->getTitle());

$urlEdit   = $this->url(
    'blog-admin/action', array('action' => 'update', 'id' => $blog->getId())
);
$urlDelete = $this->url(
    'blog-admin/action', array('action' => 'delete', 'id' => $blog->getId())
);
?>
<p><em>Datum: <?php echo $this->date($blog->getCdate()); ?></em></p>
<?php echo $blog->getContent(); ?>
<p>
<a href="<?php echo $this->url('blog'); ?>" class="btn">Zurück</a>
<?php if ($this->userIsAllowed('blog-admin')): ?>
<a href="<?php echo $urlEdit; ?>" class="btn">Beitrag bearbeiten</a>
<a href="<?php echo $urlDelete; ?>" class="btn">Beitrag löschen</a>
<?php endif; ?>
</p>
